blogsite/HerVoiceMatters/urls.py
from django.conf.urls import url
from .views import *

app_name = "Blog"
urlpatterns =[
       url(r'^$', HomeView.as_view(), name = "home"),
       url(r'^home$', HomeView.as_view(), name = "home"),
       url(r'^posts/(?P<category>\w*(delicacies|women|fashion|all))/$', PostList.as_view(), name = "posts"),
       url(r'^events$', EventList.as_view(), name = "events"),
       url(r'^gallery$', GalleryList.as_view(), name = "gallery"),
       url(r'^posts/(?P<pk>\d+)/preview/$', PostDetail.as_view(), name = "post_detail"),
       url(r'^events/(?P<pk>\d+)/preview/$', EventDetail.as_view(), name = "event_detail"),
       url(r'^contact/$', ContactView.as_view(), name = "contact"),
       url(r'^about/$', AboutView.as_view(), name = "about"),
]

blogsite/blogsite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static

urlpatterns = [

    #Admin Urls
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
    
    url(r'', include('HerVoiceMatters.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root =settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

blogsite/HerVoiceMatters/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify

# Create your models here.

class Event(models.Model):

	title = models.CharField(max_length = 200 ,default= " ")
	organizer = models.ForeignKey(User,default=1)
	event_date = models.DateTimeField(blank = False)
	location = models.CharField(max_length = 150,blank = False, null = False)
	description = models.TextField(max_length = 800)
	height_img = models.IntegerField(default = 250)
	width_img = models.IntegerField(default = 420)
	image_field = models.ImageField(upload_to ="events/",
		      null = True,
		      blank = True,
		      width_field = 'width_img',
		      height_field = "height_img",
		)
	Attending = models.IntegerField(default = 0)

	class Meta:
		ordering = ['-event_date']

	def get_absolute_url(self):
		return reverse ('Blog:event_detail', kwargs ={'pk':self.id})


class Gallery(models.Model):
	height_img = models.IntegerField(default = 250)
	width_img = models.IntegerField(default = 420)
	image_field = models.ImageField(upload_to ="gallery/",
		      null = True,
		      blank = True,
		      width_field = 'width_img',
		      height_field = "height_img",
		)
	description= models.CharField(max_length = 200)	
	created_date = models.DateTimeField(default = timezone.now)

	class Meta:
		ordering = ["-created_date"]


class Post(models.Model):
	POST_CATEGORY = (
		('fashion','FASHION'),
		('delicacies','FOOD'),
		('women','GIRL TALK'),
		) 

	author = models.ForeignKey(User,default=1)
	title = models.CharField(max_length = 200)
	category = models.CharField(max_length= 11, choices = POST_CATEGORY, default= 'fashion')
	content = models.TextField()
	height_img = models.IntegerField(default = 0)
	width_img = models.IntegerField(default = 0)
	image_field = models.ImageField(upload_to ="posts/",
		      null = True,
		      blank = True,
		      width_field = 'width_img',
		      height_field = "height_img",
		)

	created_date = models.DateTimeField(default = timezone.now)

	def __str__(self):                  
		return self.title

	def get_absolute_url(self):
		return reverse ('Blog:post_detail', kwargs ={'pk':self.id})
	class Meta:
		ordering = ["-created_date"]

blogsite/HerVoiceMatters/forms.py
from django import forms
from django.contrib.auth.models import User

class ContactForm(forms.ModelForm):
	subject = forms.CharField(max_length= 60,required = False)
	message = forms.CharField(widget=forms.Textarea, max_length = 450, required = True)

	class Meta:
		model = User
		fields = ['username','email']

class LoginForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
     
	class Meta:
		model =User
		fields = ['username','password']

class SignUpForm(forms.ModelForm):
	password = forms.CharField(widget = forms.PasswordInput)
	password2 = forms.CharField(widget = forms.PasswordInput)

	class Meta:
		model = User
		fields = ['username','email','password','password2']
	

blogsite/HerVoiceMatters/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.core.mail import send_mail, BadHeaderError
from .models import Post ,Event, Gallery
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView ,TemplateView,DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.models import User
from .forms import ContactForm,LoginForm, SignUpForm
from django.contrib.auth import authenticate,login, logout
from django.contrib import messages
from django import forms
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
#home view index page
class HomeView(TemplateView):
	template_name = 'base.html'

	def get_context_data(self, **kwargs):
		context = super(HomeView, self).get_context_data( **kwargs)
		context['events'] = Event.objects.all()[:6]
		context['gallery'] = Gallery.objects.all()[:4]
		return context


class PostList(ListView,LoginRequiredMixin):
	template_name = 'blog.html'
	context_object_name = 'posts'
	paginate_by = 3 # Show 10 posts per page

#Filter posts displayed by their category 
	def get_queryset(self,**kwargs):
		category = self.kwargs['category']

		if category is not 'all' and  not 'None':
			return Post.objects.filter(category= category)
		else:
			return Post.objects.all()

	def get_context_data(self, **kwargs):
		context = super(PostList, self).get_context_data( **kwargs)
		context['events'] = Event.objects.all()[:20]
		return context

class EventList(ListView):
	template_name = 'event_list.html'
	context_object_name= "events"
	paginate_by = 10

	def get_queryset(self):
		return Event.objects.all()

	def get_context_data(self, **kwargs):
		context = super(EventList, self).get_context_data( **kwargs)
		context['posts'] = Post.objects.all()[:20]
		return context

class GalleryList(ListView):
	template_name = "gallery.html"
	context_object_name = 'gallery'

	def get_queryset(self):
		return Gallery.objects.all()

	def get_context_data(self, **kwargs):
		context = super(GalleryList, self).get_context_data( **kwargs)
		context['posts'] = Post.objects.all()[:7]
		return context

#Model Details view

class PostDetail(DetailView):
	queryset = Post.objects.all()
	template_name = 'post_detail.html'
	context_object_name = "post"

	def get_context_data(self, **kwargs):
		context = super(PostDetail, self).get_context_data( **kwargs)  
		context['posts'] = Post.objects.all()[:7]
		return context

class EventDetail(DetailView):
	model = Event
	template_name = 'event_detail.html'
	context_object_name = "event"

	def get_context_data(self, **kwargs):
		context = super(EventDetail, self).get_context_data( **kwargs)
		context['events'] = Event.objects.all()[:5]
		return context

class ContactView(TemplateView):
	template_name = 'contact.html'
	form_class = ContactForm

	def get(self,request):
		form = self.form_class(None)
		return render(request,self.template_name, {"form":form})

	def post(self, request):
		form = self.form_class(request.POST)

		if form.is_valid():
			username = form.cleaned_data['username']
			from_email = form.cleaned_data['email']
			subject = form.cleaned_data['subject']
			message = form.cleaned_data['message']

			try:
				send_mail(subject, message, from_email, [' '])

			except BadHeaderError:
				return HttpResponse('Invalid header found.')
			messages.error(request, "MESSAGE SENT SUCCESSFULLY.")
			messages.error(request, "Thank you for your feedback.")
			return redirect('/contact')

		else:
			messages.error(request, "Please dont Leave fields blank.")
			return render(request,self.template_name,{"form":form})




class AboutView(TemplateView):
	template_name = 'about.html'

	def get_context_data(self, **kwargs):
		context = super(AboutView, self).get_context_data( **kwargs)
		context['posts'] = Post.objects.all()[:5]
		return context



#logout view
# class UserLogoutView(TemplateView):
# 	template_name = 'login.html'

# 	def get(self, request):
# 		logout(self.request)
# 		messages.error(request, "Successfully Logged out.")
# 		return redirect('blog:login')



# user  login view
# class UserLoginView(TemplateView):

# 	form_class = LoginForm
# 	template_name = 'login.html'

# 	def get(self,request):
# 		form = self.form_class(None)
# 		return render(request, self.template_name,{"form":form})

# 	def post(self,request):
# 		form = self.form_class(request.POST or None)

# 		if form.is_valid():

# 			username = form.cleaned_data['username']
# 			password = form.cleaned_data['password']

# 			user = authenticate(username= username, password= password)

# 			if user:
# 				if user.is_active:
# 					login(request,user)
# 					messages.success(request, " Welcome to HerVoiceMatters %s" %(user.username))
# 					return redirect('blog:home')
# 				else:
# 					messages.info(request, " Your account is not active, Please contact the admin" )
# 					return render(request, self.template_name,{"form":form})
# 			else:
# 				messages.error(request, " You are not a registered user or you used wrong information")
# 				return render(request, self.template_name, {"form":form})
# 		else:
# 			messages.error(request, "Please dont Leave fields blank.")
# 			return render(request, self.template_name, {"form":form})


# #signup view
# class SignUpView(CreateView):

# 	form_class = SignUpForm
# 	template_name = 'signup.html'

# 	def get(self,request):
# 		sign_form = self.form_class(None)
# 		return render(request, self.template_name,{"form":sign_form})

# 	def post(self,request):
# 		form = self.form_class(request.POST or None)

# 		if form.is_valid():
# 			new_user = form.save(commit = False )

# 			username = form.cleaned_data['username']
# 			email = form.cleaned_data['email']
# 			password = form.cleaned_data['password']
# 			password2 = form.cleaned_data['password2']

# 			#check whether username exists
# 			user,created = User.objects.get_or_create(username = username, email = email)

# 			if user and not created:
# 				messages.error(request, " The username already exist,Please choose a different one")
# 				return render(request, self.template_name, {"form":form})

# 			if len(password) >= 8:
# 				if password == password2:
# 					new_user.set_password(password)
# 					new_user.save()
# 				else:
# 					messages.error(request, " Please make sure both passwords match")
# 					return render(request, self.template_name, {"form":form})
# 			else:
# 			    messages.error(request, "your Password should be 8 characters or longer")
# 			    return render(request, self.template_name, {"form":form})

# 			return redirect('blog:login')

# 		else:
# 			return render(request, self.template_name, {'form':form})







	

blogsite/templates/hervoicematters/about.html
{% extends 'base.html' %}
{% block head %}

   {% load staticfiles %}
   <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />

      <title>{% block title %} about {% endblock %}</title>
      
      <link rel="stylesheet" href="{% static 'css/components.css' %}">
      <link rel="stylesheet" href="{% static 'css/responsee.css' %}">
      <link rel="stylesheet" href="{% static 'fas/owl-carousel/owl.carousel.css' %}">
      <link rel="stylesheet" href="{% static 'fas/owl-carousel/owl.theme.css' %}">
      <!-- CUSTOM STYLE -->  
      <link rel="stylesheet" href="{% static 'fas/css/template-style.css' %}">
      <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css'>
      <script type="text/javascript" src="{% static 'fas/js/jquery-1.8.3.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'fas/js/jquery-ui.min.js' %}"></script>    
      <script type="text/javascript" src="{% static 'fas/js/modernizr.js' %}"></script>
      <script type="text/javascript" src="{% static 'fas/js/responsee.js' %}"></script>   
      <!--[if lt IE 9]>
	      <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
      <![endif]-->
   </head>
   {% endblock %}

   
{% block section %}
   <!-- MAIN SECTION -->                  
      <section id="article-section" class="line">
         <div class="margin">
            <!-- ARTICLES -->             
            <div class="s-12 l-9">
               <!-- ARTICLE 1 -->               
               <article class="margin-bottom">
                  <!-- text -->                 
                  <div class="post-text">
                     <h1>About Us</h1>
                     <img src="{% static 'img/about.jpg' %}" alt="Fashion">
                     <p>
                        On daily basis we come across women facing different kinds of oppression and many agonizing difficulties that do not foster gender parity. All this ranges from health issues(during child birth), education (girls drop out due to pregnancies), women positioning at work places, cultural practices like FGM,and the most prevalent one, gender based violence including sexual assults.
                     </p>
                     <br>
                     <blockquote>
                        This propelled the start of this initiative in Kenya and all over the world to create awareness and be a source of power to overcome these struggles.

                     </blockquote>
                     <br>
                     <p> 
                        Her voice matters initiative aims at empowering women by providing counseling, social support as well as instilling self esteem and hope by letting the world listen to HER and changing the world perception of her strength and abilities and giving her that chance. That shred of equality that she has ever desired. 
                        We will highlight numerous activities, stories and ideas that girls and women do and face thus encourage them to sharpen their talents through fashion, food, writing, poetry, beauty and any other skill that will empower her. You are welcome to join and get involved. Thank you
            
                     </p>
                    
                  </div>
               </article>
            </div>

            <!-- SIDEBAR -->             
            <div class="s-12 l-3">
               <aside>
                  <!-- LATEST POSTS -->
                  <div class="aside-block margin-bottom">
                     <h3>Latest posts</h3>
                     {% for post in posts %}

                     <a class="latest-posts" href="#">
                        <h5>{{ post.title }}</h5>
                        <p>
                           {{ post.content|slice:":50" }}
                        </p>
                     </a>
                     <a class="latest-posts" href="post-2.html">
                        <h5>Amazing fashion blog</h5>
                        <p>
                           Ut wisi enim ad minim veniam, quis nostrud adipiscing...
                        </p>
                     </a>
                     {% endfor %}

                  </div>
                  <!-- AD REGION --> 
            
               </aside>
            </div>
         </div>
      </section>-
{% endblock %}

blogsite/templates/hervoicematters/base.html
<!DOCTYPE html>
<html lang="en-US">

{% block head %}
   <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>{% block title %} HerVoiceMatters{% endblock %}</title>

       {% load staticfiles %}
      <link rel="stylesheet" href="{% static 'css/components.css' %}">
      <link rel="stylesheet" href="{% static 'css/responsee.css' %}">
      <link rel="stylesheet" href="{% static 'owl-carousel/owl.carousel.css' %}">
      <link rel="stylesheet" href="{% static 'owl-carousel/owl.theme.css' %}">
      <!-- CUSTOM STYLE -->  
      <link rel="stylesheet" href="{% static 'css/template-style.css' %}">
      <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css'>
      <script type="text/javascript" src="{% static 'js/jquery-1.8.3.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>    
      <script type="text/javascript" src="{% static 'js/modernizr.js' %}"></script>
      <script type="text/javascript" src="{% static 'js/responsee.js' %}"></script>   
      <!--[if lt IE 9]>
	      <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
      <![endif]-->
   </head>
   {% endblock %}

    <body class="size-1140">

     {% block nav %}
      <!-- TOP NAV WITH LOGO -->
       <header>
         <nav>
            <div class="line">
               <div class="top-nav">              
                              
                  <p class="nav-text">HerVoiceMatters</p>
                  <div class="top-nav s-12 l-12">
              
                  
                     <ul class="right top-ul chevron">
                        <li><a href="{% url 'Blog:home' %}">Home</a>
                        </li>
                        <li>
                           <a>Programs</a>			    
                           <ul>
                              <li><a href="#counselling"> Counselling</a>
                              </li>
                              <li><a href="#mentorship"> Mentorship</a>
                              </li>
                              <li>
                                  <a>Talenting our skills</a>  				  
                                 <ul>
                                    <li><a href="#writing">public writing </a>
                                    </li>
                                    <li><a href="#poetry">Poetry</a>
                                    </li>
                                    <li><a href="#knitting">Knitting</a>
                                    </li>
                                 </ul>
                              </li>
                           </ul>
                        </li>
                        <li><a href="{% url 'Blog:posts' category='women' %}">Girl Talk</a> </li>

                        <li><a href="{% url 'Blog:posts' category='delicacies' %}">Food</a></li>

                        <li><a href="{% url 'Blog:posts' category='fashion' %}">Fashion</a></li>

                        <li><a href="{% url 'Blog:events' %}">Events</a></li>
                        <li><a href="{% url 'Blog:gallery' %}">Gallery</a></li>
                        <li><a href="{% url 'Blog:about' %}">About Us</a></li>
                        <li><a href="{% url 'Blog:contact' %}">Contact</a></li>
                              
                     </ul>
                  </div>
                 
               </div>
            </div>
         </nav>
      </header>
       {% endblock %} <!-- END TOP NAV  -->

         {% block section %}<!-- start of body section  -->
          
               <section>
         <!-- CAROUSEL -->  	
         <div id="carousel">
            <div id="owl-demo" class="owl-carousel owl-theme">
               <div class="item">
                  <img src="{% static "img/first.jpg" %}" alt="HerVoiceMatters">      
                  <div class="carousel-text">
                     <div class="line">
                        <div class="s-12 l-9">
                           <h2>Her Voice Matter Initiative</h2>
                        </div>
                        <div class="s-12 l-9">
                           <p>Promoting women one article at a time
                           </p>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="item">
                  <img src="{% static "img/second.jpg" %}" alt="HerVoiceMatters">      
                  <div class="carousel-text">
                     <div class="line">
                        <div class="s-12 l-9">
                           <h2>Her Voice Matter Initiative</h2>
                        </div>
                        <div class="s-12 l-9">
                           <p>Little Girls with dreams become women with vision
                           </p>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="item">
                  <img src="{% static "img/third.jpg" %}" alt="HerVoiceMatters">      
                  <div class="carousel-text">
                     <div class="line">
                        <div class="s-12 l-9">
                           <h2>Her Voice Matter Initiative</h2>
                        </div>
                        <div class="s-12 l-9">
                           <p>The symbol of Feminism and superheroism of women
                           </p>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <!-- FIRST BLOCK --> 	
         <div id="first-block">
            <div class="line">
               <h2>What we All About</h2>
               <p class="subtitile">Women Empowerment on a daily basis through fashion, Cooking ,skills developments among other programs
               </p>
               <div class="margin">
                  <a href="{% url 'Blog:posts' category='all' %}" class="s-12 m-6 l-3 margin-bottom">
                     <i class="icon-message  icon2x"></i>
                     <h3>Blog</h3>
                     <p>you can choose from our range of topics ranging from <strong>fashion</strong> to <strong>delicacies</strong> and most importantly about <strong>women</strong>.We most appreciate your valued participation in our topics.
                     </p>
                  </a>

                  <a href="{% url 'Blog:events' %}" class="s-12 m-6 l-3 margin-bottom">
                     <i class="icon-star icon2x"></i>
                     <h3>Events</h3>
                     <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
                     </p>
                  </a>

                  <a href="#" class="s-12 m-6 l-3 margin-bottom">
                     <i class="icon-paperplane_ico icon2x"></i>
                     <h3>Programs</h3>
                     <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
                     </p>
                  </a>

                  <a href="{% url 'Blog:contact' %}" class="s-12 m-6 l-3 margin-bottom">
                     <i class="icon-mail icon2x"></i>
                     <h3>Contact</h3>
                     <p>Please feel free to provide us with your feedback on the issues you would want to be talked bout ,activities you would want organized 
                     </p>
                  </a>

               </div>
            </div>
         </div>
         <!-- SECOND BLOCK --> 	
         <div id="second-block">
            <div class="line">
               <div class="margin-bottom">
                  <div class="margin">
                     <article class="s-12 l-8 center">
                        <h1>HerVoiceMatters</h1>
                        <p class="margin-bottom"> On daily basis we come across women facing different kinds of oppression and many agonizing difficulties that do not foster gender parity. All this ranges from health issues(during child birth), education (girls drop out due to pregnancies), women positioning at work places, cultural practices like FGM,and the most prevalent one, gender based violence including ....
                        </p>
                        <a class="button s-12 l-4 center" href="{% url 'Blog:about' %}">Read more</a>  			
                     </article>
                  </div>
               </div>
            </div>
         </div>
         <!-- GALLERY --> 	
         <div id="third-block">
            <div class="line">
               <h2>Events and programs gallery</h2>
               <p class="subtitile">Seeing is believing
               </p>
               <div class="margin">
               {% for image in gallery %}
                  <div class="s-12 m-6 l-3">
                     <img src="{{ image.image_field.url }}" alt="alternative text">      
                     <p class="subtitile">{{ image.description }}
                     </p>
                  </div>
                  {% endfor %}
               </div>
            </div>
         </div>

         <div id="second-block"><h2>events</h2>
            <div class="line">
               <div id="owl-demo2" class="owl-carousel owl-theme">
               {% for event in events %}
                  <a href="{% url 'Blog:event_detail' event.id %}" class="item">
                     <h3>{{event.title}} </h3>
                     <p class="s-12 m-12 l-8 center">{{ event.description |slice:":150"}}
                     </p>
                     </a>
               {% endfor %}
                  
               </div>
            </div>
         </div> <!-- END  fourth block  -->
      </section>
        {% endblock %} <!-- END  section  -->

              <!-- FOOTER --> 
             {% block footer %}  
      <footer>
         <div class="line">
            <div class="s-12 l-6">
               <p>Copyright &copy; HerVoiceMatters
               </p>
            </div>
            <div class="s-12 l-6">
               <p class="right">
                  <a class="right" href="http://www.myresponsee.com" title="Responsee - lightweight responsive framework">Design and coding </a>
               </p>
            </div>
         </div>
      </footer>
      {% endblock %} <!-- END  footer  -->
      <script type="text/javascript" src="{% static 'owl-carousel/owl.carousel.js' %}"></script>   
      <script type="text/javascript">
         jQuery(document).ready(function($) {  
           $("#owl-demo").owlCarousel({
         	slideSpeed : 300,
         	autoPlay : true,
         	navigation : false,
         	pagination : false,
         	singleItem:true
           });
           $("#owl-demo2").owlCarousel({
         	slideSpeed : 300,
         	autoPlay : true,
         	navigation : false,
         	pagination : true,
         	singleItem:true
           });
         });	
          
      </script> 
<script id="dsq-count-scr" src="//hervoicematters.disqus.com/count.js" async></script>
    
   </body>
</html>

blogsite/templates/hervoicematters/post_detail.html
{% extends 'about.html' %}
{%block title%} {{ post.title }} {% endblock %}
 {% load disqus_tags %}
 {% set_disqus_identifier "page_" page.pk %}
 {% set_disqus_title page.title %}
 {% disqus_show_comments %}
 {% disqus_dev %}

{% block section %}

      <!-- MAIN SECTION -->                  
      <section id="article-section" class="line archive">
         <div class="margin">
            <!-- ARTICLES -->             
            <div class="s-12 l-9">
            {% if post.image_field %}
            
               <!-- Post with image -->               
               <article class="margin-bottom">
                  <div class="post-1 line">
                     <!-- image -->                 
                     <div class="s-12 l-11 post-image">                   
                        <a href="{{ post.image_field.url }}"><img src="{{ post.image_field.url }}" alt="{{ post.title }}"></a>              
                     </div>
                     <!-- date -->                 
                     <div class="s-12 l-1 post-date">
                        <p class="date">{{ post.created_date|date:"d" }}</p>
                        <p class="month">{{ post.created_date|date:"b" }}</p>
                     </div>
                  </div>
                  <!-- text -->                 
                  <div class="post-text">
                     <a href="">
                        <h2>{{ post.title }}</h2>
                     </a>
                     <p>
                        {{ post.content}}
                     </p>
                  </div>
               </article>

               {% else %}
               
               <!-- If post has no image -->               
               <article class="margin-bottom">
                  <div class="post-5 line">
                     <!-- date -->                 
                     <div class="s-12 post-date">
                        <p class="date">{{ post.created_date|date:"d" }}</p>
                        <p class="month">{{ post.created_date|date:"b" }}</p>
                     </div>
                  </div>
                  <!-- text -->                 
                  <div class="post-text">
                     <a href="">
                        <h2>{{ post.title}}</h2>
                     </a>
                     <p>
                        {{ post.content}}
                     </p>
                  </div>
               </article>
 
               {% endif %}

                <!-- comments REGION -->
               <div class="line">
                  <div class="advertising horizontal"  style="background-color:#221F1F;">
<div id="disqus_thread"></div>
<script>
    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
     */
    /*
    var disqus_config = function () {
        this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    (function() {  // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        
        s.src = '//hervoicematters.disqus.com/embed.js';
        
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
    
                  </div>
               </div>

               <!-- AD REGION -->
               
            </div>


              <!-- SIDEBAR -->             
            <div class="s-12 l-3">
               <aside>
                  
                    <!-- LATEST POSTS -->
                  <div class="aside-block margin-bottom">
                     <a href="{% url 'Blog:posts' category='all'%}"><h3>Latest Posts</h3></a>
                  {% for post in posts %}
                     <a class="latest-posts" href="{% url 'Blog:post_detail' post.id %}">
                        <h5>{{ post.title }}</h5>
                        <p>
                            {{ post.content |slice:":50" }}
                        </p>
                     </a>
                     {% endfor %}
                  </div>
               </aside>
            </div>
         </div>
      </section>

{% endblock %}